# Generated by Django 2.2.7 on 2019-12-16 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('creation_date', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('user_id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('nick_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=50)),
            ],
        ),
    ]
