# Generated by Django 2.2.7 on 2019-12-16 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191216_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.IntegerField(auto_created=True, db_column='user_id', editable=False, primary_key=True, serialize=False),
        ),
    ]
