# Generated by Django 3.0.2 on 2020-01-28 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_seller_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='manufacturer_id',
            new_name='manufacturer',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='seller_id',
            new_name='seller',
        ),
    ]
