# Generated by Django 3.0.2 on 2020-02-19 13:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200128_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 19, 13, 7, 1, 747568, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
