# Generated by Django 3.0.2 on 2020-02-20 12:27

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20200220_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, height_field=40, null=True, upload_to=products.models.upload_location, width_field=40),
        ),
    ]
