# Generated by Django 3.0.2 on 2020-02-25 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20200220_1231'),
        ('products', '0004_product_expiration_date'),
    ]

    operations = [
    ]
