# Generated by Django 3.0.2 on 2020-03-02 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_merge_20200225_0922'),
        ('products', '0018_auto_20200225_1256'),
    ]

    operations = [
    ]
