# Generated by Django 3.0.2 on 2020-02-27 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_merge_20200225_0922'),
        ('products', '0019_auto_20200226_1414'),
    ]

    operations = [
    ]
