# Generated by Django 3.0.2 on 2020-03-02 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_merge_20200302_0934'),
    ]

    operations = [
    ]
